Tensor Basics

In [1]:
import torch


In [8]:
x=torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [9]:
a=torch.rand(2,2)
b=torch.rand(2,2)
print(a)
print(b)

tensor([[0.7445, 0.5377],
        [0.6258, 0.8636]])
tensor([[0.8489, 0.0917],
        [0.1729, 0.9670]])


In [11]:
b.add_(a)

tensor([[1.5934, 0.6295],
        [0.7988, 1.8306]])

In [16]:
c=torch.rand(4,4)
print(c)

tensor([[0.9067, 0.5982, 0.5900, 0.7588],
        [0.1389, 0.2979, 0.7359, 0.6581],
        [0.1456, 0.1585, 0.0523, 0.5224],
        [0.6109, 0.1047, 0.0832, 0.4587]])


In [17]:
d=c.view(-1,2)
print(d)

tensor([[0.9067, 0.5982],
        [0.5900, 0.7588],
        [0.1389, 0.2979],
        [0.7359, 0.6581],
        [0.1456, 0.1585],
        [0.0523, 0.5224],
        [0.6109, 0.1047],
        [0.0832, 0.4587]])


In [18]:
import numpy as np

In [22]:
a = np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [23]:
b=torch.from_numpy(a)
print(type(b))

<class 'torch.Tensor'>


Autograd

In [25]:
import torch

In [27]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([1.0101, 1.3532, 0.6393], requires_grad=True)


In [28]:
y=x+2
print(y)

tensor([3.0101, 3.3532, 2.6393], grad_fn=<AddBackward0>)


In [31]:
y=y.mean()
y.backward()
print(x.grad)

tensor([0.3333, 0.3333, 0.3333])


In [32]:
z=x*x

In [33]:
v=torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([0.5354, 3.0396, 0.3346])


Ways to instruct tensor not to learn from the gradient history

In [34]:
#x.requires_grad_(False)
#x.detach()
#with torch.nograd():

Way to reset grad to zero

In [35]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_op=(weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)
    
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


Backpropagation

In [63]:
 import torch

In [64]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

w=torch.tensor(1.0, requires_grad=True)

In [65]:
#forward pass
y_hat= w*x
loss=(y_hat-y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [66]:
#backward pass
loss.backward()
print(w.grad)

tensor(-2.)


gradientdescent conventional method

In [85]:
import numpy as np

In [86]:
X=np.array([1,2,3,4])
Y=np.array([2,4,6,8])

In [87]:
w=0.0

In [88]:
#output
def forward(x):
    return w*x

In [89]:
#loss=Mean squared Error
def loss(y, y_pred):
    return((y_pred-y)**2).mean()

In [90]:
def gradient(x,y,y_pred):
    return np.dot(2*x, y_pred-y).mean()

In [91]:
print(f"Prection of model before training: Forward(5) = {forward(5):.4f}")

Prection of model before training: Forward(5) = 0.0000


In [92]:
#training
lr=0.01
iteration=20

In [94]:
for epoch in range(iteration):
    y_prediction=forward(X)
    l=loss(Y,y_prediction)
    dw=gradient(X,Y, y_prediction)
    w-= lr*dw
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
print(f"Prection of model after training: Forward(5) = {forward(5):.4f}")

epoch 1: w = 1.200, loss = 30.00000000
epoch 2: w = 1.680, loss = 4.80000000
epoch 3: w = 1.872, loss = 0.76800000
epoch 4: w = 1.949, loss = 0.12288000
epoch 5: w = 1.980, loss = 0.01966080
epoch 6: w = 1.992, loss = 0.00314573
epoch 7: w = 1.997, loss = 0.00050332
epoch 8: w = 1.999, loss = 0.00008053
epoch 9: w = 1.999, loss = 0.00001288
epoch 10: w = 2.000, loss = 0.00000206
epoch 11: w = 2.000, loss = 0.00000033
epoch 12: w = 2.000, loss = 0.00000005
epoch 13: w = 2.000, loss = 0.00000001
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 18: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
epoch 20: w = 2.000, loss = 0.00000000
Prection of model after training: Forward(5) = 10.0000


Gradient descent using pytorch

In [95]:
import torch

In [97]:
X=torch.tensor([1,2,3,4], dtype=torch.float32)
Y=torch.tensor([2,4,6,8], dtype=torch.float32)

In [99]:
w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [100]:
#output
def forward(x):
    return w*x

In [101]:
#loss=Mean squared Error
def loss(y, y_pred):
    return((y_pred-y)**2).mean()

In [102]:
print(f"Prection of model before training: Forward(5) = {forward(5):.4f}")

Prection of model before training: Forward(5) = 0.0000


In [103]:
#training
lr=0.01
iteration=20

In [106]:
for epoch in range(iteration):
    y_prediction=forward(X)
    l=loss(Y,y_prediction)
    l.backward()
    with torch.no_grad():
        w-= lr*w.grad
    w.grad.zero_()
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
print(f"Prection of model after training: Forward(5) = {forward(5):.4f}")

epoch 1: w = 1.946, loss = 0.04506890
epoch 2: w = 1.954, loss = 0.02208375
epoch 3: w = 1.961, loss = 0.01595551
epoch 4: w = 1.967, loss = 0.01152786
epoch 5: w = 1.972, loss = 0.00832885
epoch 6: w = 1.976, loss = 0.00601758
epoch 7: w = 1.980, loss = 0.00434770
epoch 8: w = 1.983, loss = 0.00314120
epoch 9: w = 1.985, loss = 0.00226952
epoch 10: w = 1.987, loss = 0.00163972
epoch 11: w = 1.989, loss = 0.00118470
epoch 12: w = 1.991, loss = 0.00085596
epoch 13: w = 1.992, loss = 0.00061843
epoch 14: w = 1.993, loss = 0.00044682
epoch 15: w = 1.994, loss = 0.00032283
epoch 16: w = 1.995, loss = 0.00023325
epoch 17: w = 1.996, loss = 0.00016852
epoch 18: w = 1.997, loss = 0.00012175
epoch 19: w = 1.997, loss = 0.00008797
epoch 20: w = 1.998, loss = 0.00006356
Prection of model after training: Forward(5) = 9.9876


Training pipeline

In [110]:
import torch
import torch.nn as nn

In [114]:
X=torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y=torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

In [115]:
n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')

#samples: 4, #features: 1


In [116]:
X_test=torch.tensor([5], dtype=torch.float32)

In [117]:
input_size=n_features
output_size=n_features

In [138]:
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        self.lin=nn.Linear(input_dim, output_dim)
    
    def forward(self,x):
        return self.lin(x)

In [139]:
model=LinearRegression(input_size, output_size)

In [140]:
print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

Prediction before training: f(5) = -0.731


In [141]:
learning_rate = 0.01
n_iters = 100

In [142]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [143]:
for epoch in range(n_iters):
    
    y_predicted = model(X)

    
    l = loss(Y, y_predicted)

    
    l.backward()


    optimizer.step()


    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters() # unpack parameters
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l)

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')    

epoch  1 : w =  -0.012923809699714184  loss =  tensor(31.0836, grad_fn=<MseLossBackward>)
epoch  11 : w =  1.271174430847168  loss =  tensor(1.1372, grad_fn=<MseLossBackward>)
epoch  21 : w =  1.48968505859375  loss =  tensor(0.3430, grad_fn=<MseLossBackward>)
epoch  31 : w =  1.5364434719085693  loss =  tensor(0.3042, grad_fn=<MseLossBackward>)
epoch  41 : w =  1.5552328824996948  loss =  tensor(0.2860, grad_fn=<MseLossBackward>)
epoch  51 : w =  1.569190502166748  loss =  tensor(0.2694, grad_fn=<MseLossBackward>)
epoch  61 : w =  1.582047939300537  loss =  tensor(0.2537, grad_fn=<MseLossBackward>)
epoch  71 : w =  1.5944150686264038  loss =  tensor(0.2389, grad_fn=<MseLossBackward>)
epoch  81 : w =  1.6063989400863647  loss =  tensor(0.2250, grad_fn=<MseLossBackward>)
epoch  91 : w =  1.6180258989334106  loss =  tensor(0.2119, grad_fn=<MseLossBackward>)
Prediction after training: f(5) = 9.234


In [145]:
from sklearn import datasets

In [146]:
X_numpy, y_numpy = datasets.make_regression(n_samples=100, n_features=1, noise=20, random_state=1)

In [147]:
print(y_numpy)

[-5.55385928e+01 -1.06619847e+01  2.27574081e+01  1.01096129e+02
  1.44337558e+02  3.32888330e+01  3.30152710e+01 -2.58869694e+01
 -9.96391397e+01  2.38030714e+01 -4.55886864e+01 -8.33875709e+00
 -9.53154191e+01  3.64072963e+01 -8.72926036e+01  6.76693724e+01
 -1.36866100e+01 -5.54414224e+01 -6.53402399e+01 -5.44497141e+01
 -2.88351332e+01  1.78835048e+02  6.50839520e+01  2.66683131e+01
 -1.85459706e+01 -4.14990408e+01  8.55827764e-01  4.45616521e+01
  1.15984811e+02 -6.46197993e+01 -2.59312718e+01 -6.08820426e+01
  1.87195482e+01  7.50696998e+01  1.17203175e+02 -2.26982690e+01
 -5.63625811e+01  1.80837188e+02 -1.92574950e+02  6.85032358e+01
  1.65522025e+02  1.05000391e+02 -7.04338757e+01 -5.87693362e+01
 -4.15757142e+01  7.32472269e+01  4.09664082e+01  8.04619460e+01
 -2.87939943e+01  3.42341054e+01 -4.17148764e+01  1.43547375e+01
  7.93363240e+01  2.71292073e+01 -3.94873551e+01  6.68052070e+01
  9.55308437e+01  3.56104075e+00  1.08568943e-01  5.64952893e+01
  5.15753413e+01 -2.09741

In [148]:
print(X_numpy)

[[-0.61175641]
 [-0.24937038]
 [ 0.48851815]
 [ 0.76201118]
 [ 1.51981682]
 [ 0.37756379]
 [ 0.51292982]
 [-0.67124613]
 [-1.39649634]
 [ 0.31563495]
 [-0.63699565]
 [-0.39675353]
 [-1.10061918]
 [ 0.90085595]
 [-1.09989127]
 [ 0.82797464]
 [-0.07557171]
 [-0.35224985]
 [-0.67066229]
 [-1.07296862]
 [-0.30620401]
 [ 2.18557541]
 [ 0.86540763]
 [ 0.19829972]
 [-0.38405435]
 [-0.68372786]
 [ 0.05080775]
 [ 0.58281521]
 [ 1.25286816]
 [-0.75439794]
 [-0.34934272]
 [-0.88762896]
 [ 0.18656139]
 [ 0.87616892]
 [ 0.83898341]
 [-0.50446586]
 [-0.34385368]
 [ 1.6924546 ]
 [-2.3015387 ]
 [ 0.93110208]
 [ 2.10025514]
 [ 1.46210794]
 [-0.84520564]
 [-0.87785842]
 [-0.3224172 ]
 [ 0.88514116]
 [ 0.16003707]
 [ 1.13162939]
 [-0.37528495]
 [ 0.50249434]
 [-0.20889423]
 [ 0.12015895]
 [ 0.58662319]
 [ 0.3190391 ]
 [-0.69166075]
 [ 0.69803203]
 [ 1.19891788]
 [-0.20075807]
 [ 0.53035547]
 [ 0.74204416]
 [ 0.41005165]
 [ 0.11900865]
 [-0.7612069 ]
 [ 0.42349435]
 [ 0.30017032]
 [-1.1425182 ]
 [ 0.18515

Logistic Regression

In [187]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [188]:
breast_cancer=datasets.load_breast_cancer()
X,y = breast_cancer.data, breast_cancer.target

In [189]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [190]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [191]:
n_samples, n_features=X.shape

In [192]:
print(n_samples)
print(n_features)

569
30


In [193]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=1234)

In [194]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [195]:
X_train=torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [196]:
y_train=y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)

In [197]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model,self).__init__()
        self.linear = nn.Linear(n_input_features,1)
    
    def forward(self, x):
        y_pred=torch.sigmoid(self.linear(x))
        return y_pred

In [198]:
model=Model(n_features)

In [199]:
num_epochs = 100
learning_rate = 0.01
criterion = nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [204]:
for epoch in range(num_epochs):
    y_pred=model(X_train)
    loss=criterion(y_pred, y_train)
    loss.backward()
    optimizer.zero_grad()
    if (epoch+1) % 10 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')
with torch.no_grad():
    y_predicted = model(X_test)
    y_predicted_cls = y_predicted.round()
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

epoch: 10, loss = 0.2272
epoch: 20, loss = 0.2272
epoch: 30, loss = 0.2272
epoch: 40, loss = 0.2272
epoch: 50, loss = 0.2272
epoch: 60, loss = 0.2272
epoch: 70, loss = 0.2272
epoch: 80, loss = 0.2272
epoch: 90, loss = 0.2272
epoch: 100, loss = 0.2272
accuracy: 0.9123


Data Transformer and Data loader

In [225]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [226]:
class WineDataset(Dataset):
    def __init__(self, transform=None):
        dataset_loading=np.loadtxt('/home/gourav/Downloads/9408623-b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples=dataset_loading.shape[0]
        
        self.x_data=dataset_loading[:,1:]
        self.y_data=dataset_loading[:,[0]]
        
        self.transform=transform
        
    def __getitem__(self, index):
        sample= self.x_data[index], self.y_data[index]
        
        if self.transform:
            sample = self.transform(sample)
        
        return sample
    
    def __len__(self):
        return self.n_samples

In [227]:
class ToTensor:
    def __call__(self, sample):
        inputs, results = sample
        return torch.from_numpy(inputs), torch.from_numpy(results)

In [228]:
print('\nWith Tensor Transform')
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))
print(features, labels)


With Tensor Transform
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [229]:
train_loader=DataLoader(dataset=dataset,
                       batch_size=4,
                       shuffle=True,
                       num_workers=2)

In [230]:
dataiterator=iter(train_loader)
data=dataiterator.next()
features, labels=data
print(features, labels)

tensor([[1.3170e+01, 2.5900e+00, 2.3700e+00, 2.0000e+01, 1.2000e+02, 1.6500e+00,
         6.8000e-01, 5.3000e-01, 1.4600e+00, 9.3000e+00, 6.0000e-01, 1.6200e+00,
         8.4000e+02],
        [1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+03],
        [1.2040e+01, 4.3000e+00, 2.3800e+00, 2.2000e+01, 8.0000e+01, 2.1000e+00,
         1.7500e+00, 4.2000e-01, 1.3500e+00, 2.6000e+00, 7.9000e-01, 2.5700e+00,
         5.8000e+02],
        [1.4060e+01, 2.1500e+00, 2.6100e+00, 1.7600e+01, 1.2100e+02, 2.6000e+00,
         2.5100e+00, 3.1000e-01, 1.2500e+00, 5.0500e+00, 1.0600e+00, 3.5800e+00,
         1.2950e+03]]) tensor([[3.],
        [1.],
        [2.],
        [1.]])


In [231]:
num_epochs=2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples, n_iterations)

178 45
